# Project: DeBonteFroggerClone
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = DeBonteFroggerClone_private.res
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"C:/Users/Christopher/Desktop/Graphics/Dev-CppPortable/App/devcpp/lib" -mwindows -lalleg_s -lkernel32 -luser32 -lgdi32 -lcomdlg32 -lole32 -ldinput -lddraw -ldxguid -lwinmm -ldsound 
INCS =  -I"C:/Users/Christopher/Desktop/Graphics/Dev-CppPortable/App/devcpp/include" 
CXXINCS =  -I"C:/Users/Christopher/Desktop/Graphics/Dev-CppPortable/App/devcpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Users/Christopher/Desktop/Graphics/Dev-CppPortable/App/devcpp/include/c++/3.4.2/backward"  -I"C:/Users/Christopher/Desktop/Graphics/Dev-CppPortable/App/devcpp/include/c++/3.4.2/mingw32"  -I"C:/Users/Christopher/Desktop/Graphics/Dev-CppPortable/App/devcpp/include/c++/3.4.2"  -I"C:/Users/Christopher/Desktop/Graphics/Dev-CppPortable/App/devcpp/include" 
BIN  = DeBonteFroggerClone.exe
CXXFLAGS = $(CXXINCS) -DALLEGRO_STATICLINK 
CFLAGS = $(INCS) -DALLEGRO_STATICLINK 
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before DeBonteFroggerClone.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "DeBonteFroggerClone.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

DeBonteFroggerClone_private.res: DeBonteFroggerClone_private.rc 
	$(WINDRES) -i DeBonteFroggerClone_private.rc --input-format=rc -o DeBonteFroggerClone_private.res -O coff 
